### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by qtsky89** [qtsky89/portfolio#1]
## Architecture
![Architecture](https://user-images.githubusercontent.com/5737187/102193103-00723780-3eff-11eb-90ee-4969eaeea60f.png)

## Mockups
* Let's start like following mockups.
![Overall](https://user-images.githubusercontent.com/5737187/102189803-8cce2b80-3efa-11eb-8183-dffb4146ade3.png)
![Each Project](https://user-images.githubusercontent.com/5737187/102189810-8e97ef00-3efa-11eb-9f2a-92873c2daacd.png)

**Comment by qtsky89** [comment]
## ToDo
* [x] Django server setting
* [x] Add project_view.py.
* [x] project image.
* [x] hover + click feature.
