### ISSUE TITLE
Serve portfolio using AWS resource

### ISSUE THREAD

**Issue by qtsky89** [qtsky89/portfolio#3]
## Issue
* Serve portfolio using AWS resource

## ToDo
* [x] learn how to use https
* [x] Make backend, frontend image
* [x] Make docker-compose file
* [x] Serve!
